title: IndexStraddleBacktesting
description: Develop a code to test straddle strategy
template:
  repo: indexstraddlebacktesting-template
  name: indexstraddlebacktesting
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
